---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/dynatrace-cli
    tag: "latest"

inputs:
- name: git-pipeline
- name: git-user
  optional: true
- name: git-orders
  optional: true
#- name: current-app-info

run:
  path: ./git-pipeline/deploy/cloud-foundry/ci/tasks/init-dynatrace-task